// Auto-generated from Current.csv (10 active listings) and Rex_Listings.csv
// (10 most recent sold listings, picked by highest mlsId).
// Real addresses, real prices, real photos pulled straight from the agency's CRM export.
//
// NOTE (v4): this file is only read ONCE, on first boot, to seed data/listings.json.
// After that every change happens in the dashboard. Editing this file later does nothing.

const CURRENT_LISTINGS = [
  {
    "id": "4978167",
    "status": "current",
    "title": "Freshly Updated, Wonderfully Central & Ready to Enjoy",
    "address": "81 Springfield Road, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "Contact Agent",
    "priceNumeric": null,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 1,
    "landSize": "575 m²",
    "description": "Perfectly positioned in one of Springfield's most convenient locations, this beautifully presented home delivers the ideal balance of character, comfort and practicality. Freshly painted throughout and showcasing beautiful hardwood timber flooring, it offers a warm and welcoming feel from the moment you arrive, while its central location places schools, shopping, transport and…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/4978167/images/DJI_20260626122551_0_978f-e7bd-38b8-34a4-d6ec-1df0-24ec-faba_20260629125448.jpg"
  },
  {
    "id": "5127233",
    "status": "current",
    "title": "A Private Family Retreat Designed for Modern, Low-Maintenance Living",
    "address": "7 Dulwich Road, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "Contact Agent",
    "priceNumeric": null,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 2,
    "landSize": "518 m²",
    "description": "Not every home manages to strike the balance between relaxed family living and refined modern style. Behind its immaculately presented façade, this residence delivers exactly that. Thoughtfully renovated, beautifully maintained and designed for the way families actually live, it's the kind of home where sunny mornings, effortless entertaining and quiet evenings all feel…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5127233/images/DSC09022_dccf-decd-9b76-16a9-cc00-7f3b-9cf0-b189_20260608111922.jpg"
  },
  {
    "id": "5133666",
    "status": "current",
    "title": "A Charming Family Home.",
    "address": "7 Bilkurra Place, Niagara Park NSW 2250",
    "suburb": "Niagara Park",
    "priceDisplay": "Contact Agent",
    "priceNumeric": null,
    "bedrooms": 3,
    "bathrooms": 1,
    "parking": 3,
    "landSize": "695 m²",
    "description": "From the elevated front balcony framed by leafy surrounds to the generous covered entertaining area overlooking the backyard, this is a home that naturally encourages you to slow down and enjoy where you live. Whether it's your morning coffee on the deck, hosting family and friends outdoors or watching the kids and pets play safely on the lawn, every space has been…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5133666/images/DSC02646-copy_dc42-7912-d689-20c4-97c0-bf21-d3c4-1e86_20260709032017.jpg"
  },
  {
    "id": "5162337",
    "status": "current",
    "title": "Light Filled, Easy Living in a Peaceful Saratoga Setting",
    "address": "2 / 1 Frederick Goddard Close, Saratoga NSW 2251",
    "suburb": "Saratoga",
    "priceDisplay": "For Sale",
    "priceNumeric": null,
    "bedrooms": 2,
    "bathrooms": 1,
    "parking": 1,
    "landSize": "0 m²",
    "description": "Tucked away in a quiet and leafy Saratoga pocket, 2/1 Frederick Goddard Close offers the simplicity of single-level living with a warm, welcoming feel from the moment you arrive. Freshly painted and finished with brand-new carpet, the home is bright, comfortable and ready to enjoy. At the heart of the home, the spacious living and meals area connects easily with the practical…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5162337/images/DSC06275_0dfc-83b6-8d85-409d-c48f-0202-623a-2d38_20260824124605.jpg"
  },
  {
    "id": "5162996",
    "status": "current",
    "title": "A Rare Terrigal Block With Sun, Space and Possibility",
    "address": "86 Willoughby Road, Terrigal NSW 2260",
    "suburb": "Terrigal",
    "priceDisplay": "For Sale",
    "priceNumeric": null,
    "bedrooms": 3,
    "bathrooms": 1,
    "parking": 1,
    "landSize": "695 m²",
    "description": "Set on approximately 695m² with an 18-metre frontage, 86 Willoughby Road offers something increasingly difficult to find in Terrigal — a near-level, sun-filled block with genuine space around the home and plenty of flexibility for the future. The existing three-bedroom residence provides a comfortable and practical starting point, with polished timber floors, generous living…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5162996/images/1Y2A6140_965a-2a46-04dd-7985-e23b-ad8c-8489-d47a_20260721124141.jpg"
  },
  {
    "id": "5174185",
    "status": "current",
    "title": "Space, Scale & Potential",
    "address": "25 North Crescent, North Gosford NSW 2250",
    "suburb": "North Gosford",
    "priceDisplay": "$849,000 - $899,000",
    "priceNumeric": 849000,
    "bedrooms": 5,
    "bathrooms": 2,
    "parking": 1,
    "landSize": "607 m²",
    "description": "Offering generous proportions across two levels, 25 North Crescent presents an exciting opportunity for buyers looking for a substantial family home with plenty of room to make their mark. While the property is in need of renovation and updating, its underlying space and flexible layout provide an excellent foundation for those ready to transform it into something special. The…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5174185/images/DSC09492_6b02-6a12-65e2-71bc-760c-cff7-9083-7b33_20260823113823.jpg"
  },
  {
    "id": "5216151",
    "status": "current",
    "title": "Where Coastal Luxury Comes Naturally",
    "address": "5 / 120 Swadling Street, Toowoon Bay NSW 2261",
    "suburb": "Toowoon Bay",
    "priceDisplay": "$1,290,000 - $1,390,000",
    "priceNumeric": 1290000,
    "bedrooms": 3,
    "bathrooms": 3,
    "parking": 2,
    "landSize": "0 m²",
    "description": "A refined expression of contemporary coastal living, this beautifully appointed townhouse delivers an exceptional sense of luxury just moments from the shoreline of Toowoon Bay. Soaring ceilings, streams of natural light and floor-to-ceiling sheer curtains create an immediate feeling of space and serenity, while warm engineered timber flooring and considered finishes bring…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5216151/images/DSC03548_943c-aabd-63eb-1e17-3e11-8a33-1103-148e_20260807014040.jpg"
  },
  {
    "id": "5231037",
    "status": "current",
    "title": "A Beautifully Renovated Home Among The Canopies",
    "address": "7 Rubie Crescent, East Gosford NSW 2250",
    "suburb": "East Gosford",
    "priceDisplay": "For Sale",
    "priceNumeric": null,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 1,
    "landSize": "569 m²",
    "description": "Elevated into the treetops with a private leafy outlook and glimpses of Brisbane Water beyond, 7 Rubie Crescent delivers a rare combination of scale, privacy and beautifully finished modern living. Renovated throughout, the home feels fresh and considered from top to bottom, with generous proportions that give every room a genuine sense of space. Inside, the transformation is…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5231037/images/Rubie-Crs-Dusk-Facad_8c9e-c604-019e-e034-69de-74af-ac6c-50bf_20260831042913.jpg"
  },
  {
    "id": "5231851",
    "status": "current",
    "title": "More Than Meets The Eye",
    "address": "13 Headlam Parade, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "For Sale",
    "priceNumeric": null,
    "bedrooms": 3,
    "bathrooms": 2,
    "parking": 1,
    "landSize": "595 m²",
    "description": "Behind its charming street presence, 13 Headlam Parade delivers far more space than first impressions suggest. Generous proportions, multiple living areas and an impressive backyard with an in-ground pool come together to create a substantial family home with plenty to enjoy today and genuine scope to make your own over time. Stepping inside, the scale of the home quickly…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5231851/images/DJI_20260818121202_0_66e6-fd90-e74b-8fe8-d6af-221a-e1b3-78c3_20260819011020.jpg"
  },
  {
    "id": "5241273",
    "status": "current",
    "title": "Modern Single-Level Living, Ready To Enjoy",
    "address": "10 Lakala Avenue, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "For Sale",
    "priceNumeric": null,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 2,
    "landSize": "515 m²",
    "description": "Built in 2015 and designed around easy everyday living, 10 Lakala Avenue delivers the kind of modern single-level floorplan that continues to appeal to a wide range of buyers. Bright interiors, generous proportions and a practical connection between the main living spaces and backyard create a home that feels comfortable from the moment you step inside. The open-plan kitchen,…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5241273/images/Front-RE-WEB-2_7d37-2c1b-ed80-910b-36ee-0825-4842-7232_20260901121606.jpg"
  }
];

const SOLD_LISTINGS = [
  {
    "id": "5177886",
    "status": "sold",
    "title": "SOLD by Edan Sirone & James Keelan",
    "address": "1 Mayfair Close, Terrigal NSW 2260",
    "suburb": "Terrigal",
    "priceDisplay": "$1,530,000",
    "priceNumeric": 1530000,
    "bedrooms": 3,
    "bathrooms": 2,
    "parking": 2,
    "landSize": "700 m²",
    "description": "Tucked away within one of Terrigal’s most tightly held pockets, 1 Mayfair is a home that immediately captures your imagination. Solidly constructed in double brick and framed by established botanical-style gardens, it offers the space, character and foundations to create something truly special. Sunlight streams through the generous interiors, while soaring 10-foot ceilings…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5177886/images/DJI_20260731172912_0_1f97-caf3-861a-6fd5-beae-d7cb-0c4b-ad61_20260803012946.jpg"
  },
  {
    "id": "5162024",
    "status": "sold",
    "title": "SOLD by James Keelan & Edan Sirone",
    "address": "11 River Street, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$930,000",
    "priceNumeric": 930000,
    "bedrooms": 4,
    "bathrooms": 1,
    "parking": 1,
    "landSize": "518 m²",
    "description": "Positioned in one of Springfield's most sought-after family pockets, this beautifully presented single-level home combines everyday comfort with a practical layout designed for modern living. Offering four generous bedrooms, light-filled interiors and a spacious open-plan design, this is a home that caters effortlessly to growing families, first home buyers and savvy investors…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5162024/images/1-Edit-1-_a8d6-670b-c8d2-3fc6-ba7b-5ea9-0111-1bf3_20260630021206.jpg"
  },
  {
    "id": "5144887",
    "status": "sold",
    "title": "SOLD by James Keelan & Edan Sirone",
    "address": "12 Dolly Avenue, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$853,000",
    "priceNumeric": 853000,
    "bedrooms": 3,
    "bathrooms": 1,
    "parking": 2,
    "landSize": "607 m²",
    "description": "Warm, welcoming and filled with timeless character, this beautifully maintained residence offers the kind of home that simply feels right from the moment you step inside. Combining charming original features with generous proportions and a practical family-focused layout, every space has been thoughtfully designed to encourage connection, comfort and easy everyday living. At…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5144887/images/DJI_20260629121013_0_1d1e-1caa-1427-110a-e7f2-176f-b8c9-7028_20260701065424.jpg"
  },
  {
    "id": "5133666",
    "status": "sold",
    "title": "SOLD by Sophia Lamont & James Keelan",
    "address": "7 Bilkurra Place, Niagara Park NSW 2250",
    "suburb": "Niagara Park",
    "priceDisplay": "$925,000",
    "priceNumeric": 925000,
    "bedrooms": 3,
    "bathrooms": 1,
    "parking": 3,
    "landSize": "695 m²",
    "description": "From the elevated front balcony framed by leafy surrounds to the generous covered entertaining area overlooking the backyard, this is a home that naturally encourages you to slow down and enjoy where you live. Whether it's your morning coffee on the deck, hosting family and friends outdoors or watching the kids and pets play safely on the lawn, every space has been…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5133666/images/DSC02646-copy_dc42-7912-d689-20c4-97c0-bf21-d3c4-1e86_20260709032017.jpg"
  },
  {
    "id": "5127103",
    "status": "sold",
    "title": "SOLD by James Keelan & Edan Sirone",
    "address": "39 Dolly Avenue, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$970,000",
    "priceNumeric": 970000,
    "bedrooms": 3,
    "bathrooms": 2,
    "parking": 2,
    "landSize": "695 m²",
    "description": "Beautifully renovated and thoughtfully designed for modern family living, this warm and inviting home delivers the perfect balance of space, privacy and convenience. Set in an exceptionally central location, you'll feel a world away from it all as you overlook peaceful bushland surrounds, yet remain only minutes from everything the Central Coast has to offer. At the heart of…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5127103/images/Facade-1-_ebb9-0011-7456-2fc5-2c8e-bc27-c7b1-4181_20260622120002.jpg"
  },
  {
    "id": "5123389",
    "status": "sold",
    "title": "SOLD by James Keelan & Edan Sirone",
    "address": "15a Carrabella Avenue, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$1,540,000",
    "priceNumeric": 1540000,
    "bedrooms": 4,
    "bathrooms": 3,
    "parking": 2,
    "landSize": "600 m²",
    "description": "Sold prior to marketing!!! Thinking of selling or just curious about your property's value? Contact James Keelan today on 0435 714 565 for a free, no-obligation market appraisal. DISCLAIMER: The information in this advertisement has been provided by third parties. While PropertyCo Services strives to ensure its accuracy, we do not guarantee or warrant its completeness. We…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5123389/images/SOLD-OFF-MARKET-15A-_5ae0-3ee5-cd8f-7187-5a1c-edd5-05c3-1d8f_20260610125016.jpg"
  },
  {
    "id": "5119384",
    "status": "sold",
    "title": "SOLD by James Keelan & Edan Sirone",
    "address": "12 / 20 Springfield Road, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$820,000",
    "priceNumeric": 820000,
    "bedrooms": 3,
    "bathrooms": 1,
    "parking": 1,
    "landSize": "0 m²",
    "description": "There is something undeniably comforting about this home. Thoughtfully renovated with a warm coastal feel, it offers a beautiful balance of modern convenience and relaxed living. Filled with natural light and designed for easy everyday living, the open-plan kitchen, living and dining area creates a welcoming heart of the home where family and friends can naturally come…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5119384/images/DSC09568_e805-be8a-3a6b-6309-1f16-d85e-589b-acad_20260614111312.jpg"
  },
  {
    "id": "5101096",
    "status": "sold",
    "title": "SOLD by James Keelan & Edan Sirone",
    "address": "27 River Street, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$1,020,000",
    "priceNumeric": 1020000,
    "bedrooms": 3,
    "bathrooms": 2,
    "parking": 2,
    "landSize": "518 m²",
    "description": "A sense of warmth hits you the moment you step inside. Elevated to capture light and space, this beautifully maintained brick and tile residence blends soaring ceilings, oversized interiors and a flexible family layout. The main living, dining and kitchen zone feels immediately inviting with its rich flooring, impressive ceiling height and seamless flow throughout. Large…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5101096/images/Facade-1_9864-e83a-7fb9-0051-8e90-631e-503d-efe3_20260525121225.jpg"
  },
  {
    "id": "5096784",
    "status": "sold",
    "title": "SOLD by James Keelan & Edan Sirone",
    "address": "21 Robinia Parade, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$1,260,000",
    "priceNumeric": 1260000,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 2,
    "landSize": "603 m²",
    "description": "Beautifully framed by manicured hedging and an inviting street presence, this stunning residence immediately sets a calming tone from the moment you arrive. Thoughtfully updated throughout with warm timber flooring, soft natural light and beautifully balanced interiors, the home delivers a rare blend of sophistication and genuine everyday comfort in one of Springfield’s most…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5096784/images/DSC06052-2_165e-5eea-e086-1ce0-24c2-ce51-9fdd-f6b5_20260520013947.jpg"
  },
  {
    "id": "5089548",
    "status": "sold",
    "title": "SOLD by James Keelan & Sophia Lamont",
    "address": "109 Wells Street, Springfield NSW 2250",
    "suburb": "Springfield",
    "priceDisplay": "$1,140,000",
    "priceNumeric": 1140000,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 1,
    "landSize": "695 m²",
    "description": "Beautifully renovated and thoughtfully designed for modern family living, this warm and inviting single-level residence offers the perfect balance of comfort, functionality and elevated contemporary style. With expansive living spaces, quality finishes and substantial upgrades already completed, the home delivers a turnkey lifestyle ideal for growing families or professional…",
    "heroImageUrl": "https://au-crm.cdns.rexsoftware.com/app/livestore/accounts/145/listings/5089548/images/Front_98ef-ea39-ee56-ff44-6197-2503-d075-974a_20260518115327.jpg"
  }
];

module.exports = { CURRENT_LISTINGS, SOLD_LISTINGS };